language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://dbarber.pact.dius.com.au
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "CDQDAtImICG9hmS6KtJSh1iCVGbu1nW+soZjtBFHOv+sHqWXQsDGYSqzGdx2hLcp2fP1EuHR45dCyQpUwpH16HKaqVOAYoxNG8qSbG8nwzhQuxbsqZSVLss9rSOS8aNN5+TokpUrhnLe1X1rg8MyiYF2wK6o++oFC+QoqX7gpL/z/Dx/iEuozagrlvHQb475E8X0GM7MH/D8fTAlH1dYXguVJ+c6LVtRe8JpYaCuwRvQW08cPcAEw+0NFb6uH6l1FbXqhYZynbQukNjMtWRfpgJH6rarUpRcjJnlhbvQGdsDhfdhAQZR5GWhOFm7Rt7KPu1ZZ+WSGYWfqPWHos78+ycnt8bUiFgfzxFODCfrHDj9LdYoCWtiq34lpJmZOR1czufcXCgTWCk7gjtqojzAg5MH5HWsStQ9KwcxLZdJaW5rmGA6tWVWqMm99TQlFdrK4Cf5mxh9+sBuVAB+z+H/M8NWW5S7lOci4UPKU1CysOgOn64Yj8/ZctQ+PjgLsRKCwBAN08jvCrSWIeV+ZhWZsjLlYq3EGWugAeeKcekMWtgRjyLyAVrkHE521asHNxuy6AF7m1SQVN2SVwnFeMk/RqY5lnSTcbwQHnmEytKzKT3yw3mwiGHF/0BqfzhWEr1hctwSux+MhPnhVDqVQsrJFUpLpEtHQSW9qielXBOWqdY="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
